import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { ConfigProvider, useConfig } from "@contexts"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  // const config = useConfig()

  // className={inter.className}
  return (
    <html lang="en">
      {/* <ConfigProvider value={context}> */}
      <body>{children}</body>
      {/* </ConfigProvider> */}
    </html>
  )
}
