<<<<<<< HEAD
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
=======
import localFont from 'next/font/local'
import { ThemeProvider } from 'next-themes'

import "./globals.css"

const myFont = localFont({
  src: "../public/fonts/latinmodern-math.woff2",
  variable: '--font-latexmath',
})


export const metadata = {
  title: 'MillionScope',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${myFont.variable}`}>
      <body>
        
        {children}</body>
    </html>
  )
>>>>>>> origin/dev
}
