import localFont from 'next/font/local'
import { ThemeProvider } from 'next-themes'

import "./globals.css"
import "./styles.css"
import "./custom.css"
import MyHeader from '@/components/myheader'
import MyFooter from '@/components/myfooter'
import MyBodyBlog from '@/components/body'
import MyBlog from '@/components/blog'

const myFont = localFont({
  src: "../public/fonts/latinmodern-math.woff2",
  variable: '--font-latexmath',
})


export const metadata = {
  title: 'MillionScope',
  descriptison: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${myFont.variable} js-focus-visible light`} style={{ colorScheme: "light" }} dir="ltr" data-js-focus-visible>
      <body>
        <div className="" dir="ltr">
          <MyHeader></MyHeader>
          {/* <BodyBlog>{children}</BodyBlog> */}
          <MyBlog>{children}</MyBlog>
          <MyFooter></MyFooter>
        </div>
      </body>
    </html>
  )
}
