import localFont from 'next/font/local'

import "./globals.css"

const myFont = localFont({
  src: "../public/fonts/latinmodern-math.woff2",
  variable: '--font-latexmath',
})


export const metadata = {
  title: 'MillionScope',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${myFont.variable}`}>
      <body>{children}</body>
    </html>
  )
}
